---
title: "lab06"
author: "Megan Tran"
date: '`September 28, 2022'
output: github_document
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r install-libraries}
library(tidytext)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(forcats)
```

## 1. Read in the data
```{r read-data, cache=TRUE}
if (!file.exists("mtsamples.csv")) {
download.file("https://raw.githubusercontent.com/USCbiostats/data-science-data/master/00_mtsamples/mtsamples.csv", "mtsamples.csv", method="libcurl", timeout = 60) 
}
mts <- read.csv("mtsamples.csv") 
str(mts)
mts <- as_tibble(mts)
mts
```

##Question 1: What specialties do we have?

We can use count() from dplyr to figure out how many records are there per specialty?

```{r medical-specialties}
specialties <-
    mts %>%
    count(medical_specialty)

specialties %>%
  arrange(desc(n)) %>%
knitr::kable()
```

There are 'r nrow(specialties)' medical specialties.

```{r barplot-of-specialty-counts}
specialties %>%
  top_n(10) %>%
  ggplot( aes(x = n, y = fct_reorder(medical_specialty,n))) + 
    geom_col()
```

The distribution is not at all uniform.


